"""
agents.py

Contains concrete agent functions returning detailed prompts for extracting and mapping
BRSR data for Section A, Section B, and grouped Principles. Each function returns a dict
containing `role`, `goal`, and `prompt` (string). Prompts enumerate the exact keys and the
expected data type/format for each key so an extraction agent (LLM) can populate the
corresponding JSON fields deterministically.

Do not instantiate external Agent classes here — these functions return the fully
specified prompt payloads that can be passed to whatever Agent wrapper is used in the
project.
"""

from typing import Dict


def create_sectionA_agent() -> Dict[str, str]:
    """Return prompt payload for Section A extraction using simple key-value array format."""
    role = "BRSR Section A Extraction Specialist"
    goal = "Extract Section A fields and return a JSON array of key-value pairs"
    prompt = (
        "You are an assistant that MUST output only valid JSON.\n\n"
        "Extract the following fields from the company data and output a JSON array of objects:\n"
        '[{"key": "<field_key>", "value": "<extracted_value>"}]\n\n'
        "RULES:\n"
        "- Only include fields you can extract exactly from the text\n"
        "- If a value is absent, use null or empty string\n"
        "- Do NOT add commentary or explanations\n"
        "- Output MUST be valid JSON array\n"
        "- For numbers, return as strings (e.g., \"3424\" not 3424)\n"
        "- For arrays/tables, return as JSON string array\n"
        "- Do NOT wrap output in markdown code blocks (no ``` or ```json)\n\n"
        "Fields to extract:\n\n"
        "I. Details of the Listed Entity (Q1-Q15):\n"
        "sectiona_cin, sectiona_entityName, sectiona_yearOfIncorporation, "
        "sectiona_registeredAddress, sectiona_corporateAddress, sectiona_email, "
        "sectiona_telephone, sectiona_website, sectiona_financialYear, "
        "sectiona_stockExchanges, sectiona_paidUpCapital, "
        "sectiona_contactName, sectiona_contactDesignation, sectiona_contactPhone, sectiona_contactEmail, "
        "sectiona_reportingBoundary, sectiona_assuranceProvider, sectiona_assuranceType\n\n"
        "II. Products/Services (Q16-Q17):\n"
        "sectiona_businessActivities_array (JSON array string: [{\"mainActivity\":\"...\",\"businessDescription\":\"...\",\"turnoverPercent\":\"...\"}]), "
        "sectiona_products_array (JSON array string: [{\"name\":\"...\",\"nicCode\":\"...\",\"turnoverPercent\":\"...\"}])\n\n"
        "III. Operations (Q18-Q19):\n"
        "sectiona_nationalPlants, sectiona_nationalOffices, sectiona_internationalPlants, sectiona_internationalOffices, "
        "sectiona_nationalStates, sectiona_internationalCountries, sectiona_exportContribution\n\n"
        "IV. Employees (Q20-Q22):\n"
        "NOTE: Contact details (contactName, contactDesignation, contactPhone, contactEmail), reportingBoundary, "
        "employee counts, worker counts, and turnover rates may be provided by user via frontend form. "
        "If you find these fields in the document, extract them normally - they will be merged with user inputs later.\n"
        "sectiona_employees_permanent_male, sectiona_employees_permanent_female, sectiona_employees_permanent_total, "
        "sectiona_employees_otherthanpermanent_male, sectiona_employees_otherthanpermanent_female, sectiona_employees_otherthanpermanent_total, "
        "sectiona_workers_permanent_male, sectiona_workers_permanent_female, sectiona_workers_permanent_total, "
        "sectiona_workers_otherthanpermanent_male, sectiona_workers_otherthanpermanent_female, sectiona_workers_otherthanpermanent_total, "
        "sectiona_board_total, sectiona_board_female, sectiona_board_femalePercent, "
        "sectiona_kmp_total, sectiona_kmp_female, sectiona_kmp_femalePercent, "
        "sectiona_turnover_employees_male, sectiona_turnover_employees_female, sectiona_turnover_employees_total, "
        "sectiona_turnover_workers_male, sectiona_turnover_workers_female, sectiona_turnover_workers_total\n\n"
        "V. Holding/Subsidiary Companies (Q23):\n"
        "sectiona_subsidiaries (Format as numbered list string: '1. Company Name (Relationship) 2. Company Name (Relationship)...'. Include CIN in parentheses if available. If none, use 'NA')\n\n"
        "VI. CSR Details (Q24):\n"
        "sectiona_csr_prescribedAmount (Look for: 1) Explicitly stated prescribed CSR amount, 2) If not found, calculate as 2% of average net profit from last 3 years, 3) If profit not available, look for turnover/net worth in CSR section and state them with label, 4) If truly NA, use 'NA'), "
        "sectiona_csr_amountSpent (Look for: 1) Actual CSR expenditure/amount spent during the year, 2) Total CSR spent, 3) If NA, use 'NA'), "
        "sectiona_csr_surplus (Look for: 1) Surplus/(deficit) explicitly stated, 2) Calculate as: Amount Spent minus Prescribed Amount if both available, 3) Unspent CSR amount, 4) If NA, use 'NA')\n"
        "IMPORTANT: For CSR, even if main answer says 'NA', check if there's a sub-section with turnover/net worth/profit data and extract those actual numbers\n\n"
        "VII. Transparency (Q25-Q26):\n"
        "sectiona_complaints_communities_filed, sectiona_complaints_communities_pending, sectiona_complaints_communities_remarks, "
        "sectiona_complaints_investors_filed, sectiona_complaints_investors_pending, sectiona_complaints_investors_remarks, "
        "sectiona_complaints_shareholders_filed, sectiona_complaints_shareholders_pending, sectiona_complaints_shareholders_remarks, "
        "sectiona_complaints_employees_filed, sectiona_complaints_employees_pending, sectiona_complaints_employees_remarks, "
        "sectiona_complaints_customers_filed, sectiona_complaints_customers_pending, sectiona_complaints_customers_remarks, "
        "sectiona_complaints_valuechain_filed, sectiona_complaints_valuechain_pending, sectiona_complaints_valuechain_remarks, "
        "sectiona_materialIssues_array (JSON array - extract ALL material issues with their details including rationale, mitigation approach, and financial implications)\n\n"
        "Example output format:\n"
        '[\n'
        '  {"key": "sectiona_cin", "value": "L17111PB1973PLC003345"},\n'
        '  {"key": "sectiona_entityName", "value": "Vardhman Textiles Limited"},\n'
        '  {"key": "sectiona_stockExchanges", "value": "BSE, NSE"},\n'
        '  {"key": "sectiona_businessActivities_array", "value": "[{\\"mainActivity\\":\\"Textile Manufacturing\\",\\"businessDescription\\":\\"Manufacturing of different types of yarn & fabric and garments\\",\\"turnoverPercent\\":\\"99.60\\"}]"},\n'
        '  {"key": "sectiona_products_array", "value": "[{\\"name\\":\\"Yarn, Fabric & Garments\\",\\"nicCode\\":\\"131\\",\\"turnoverPercent\\":\\"99.60\\"}]"},\n'
        '  {"key": "sectiona_subsidiaries", "value": "1. Vardhman Acrylics Limited (Subsidiary) 2. VTL Investments Limited (Subsidiary) 3. Vardhman Special Steels Limited (Associate)"},\n'
        '  {"key": "sectiona_csr_prescribedAmount", "value": "185.88 Crores"},\n'
        '  {"key": "sectiona_nationalPlants", "value": "15"},\n'
        '  {"key": "sectiona_employees_permanent_male", "value": "3424"}\n'
        ']\n'
    )

    return {"role": role, "goal": goal, "prompt": prompt}


def create_sectionB_agent() -> Dict[str, str]:
    """Return prompt payload for Section B extraction using simple key-value array format.
    Note: Only extracts ALL Section B fields from PDF. Manual input form only allows Policy Matrix + policyWebLink.
    """
    role = "BRSR Section B Extraction Specialist"
    goal = "Extract Section B governance & policy fields and return a JSON array of key-value pairs"
    prompt = (
        "You are an assistant that MUST output only valid JSON.\n\n"
        "Extract the following fields from the company data and output a JSON array of objects:\n"
        '[{"key": "<field_key>", "value": "<extracted_value>"}]\n\n'
        "RULES:\n"
        "- Only include fields you can extract exactly from the text\n"
        "- If a value is absent, use null or empty string\n"
        "- Do NOT add commentary or explanations\n"
        "- Output MUST be valid JSON array\n"
        "- For Yes/No fields, use 'Y' or 'N' strings\n"
        "- For URLs, return full http/https link\n"
        "- Do NOT wrap output in markdown code blocks (no ``` or ```json)\n\n"
        "SECTION B: MANAGEMENT AND PROCESS DISCLOSURES\n\n"
        "Q1. Policy and management processes - Policy Matrix (P1-P9):\n"
        "For each principle (P1-P9), extract:\n"
        "- hasPolicy: Whether policy covers this principle (Y/N)\n"
        "- approvedByBoard: Whether approved by Board (Y/N)\n"
        "- webLink: URL if available\n"
        "- translatedToProcedures: Whether policy translated to procedures (Y/N)\n\n"
        "Fields:\n"
        "sectionb_policymatrix_p1_hasPolicy, sectionb_policymatrix_p1_approvedByBoard, sectionb_policymatrix_p1_webLink, sectionb_policymatrix_p1_translatedToProcedures, "
        "sectionb_policymatrix_p2_hasPolicy, sectionb_policymatrix_p2_approvedByBoard, sectionb_policymatrix_p2_webLink, sectionb_policymatrix_p2_translatedToProcedures, "
        "sectionb_policymatrix_p3_hasPolicy, sectionb_policymatrix_p3_approvedByBoard, sectionb_policymatrix_p3_webLink, sectionb_policymatrix_p3_translatedToProcedures, "
        "sectionb_policymatrix_p4_hasPolicy, sectionb_policymatrix_p4_approvedByBoard, sectionb_policymatrix_p4_webLink, sectionb_policymatrix_p4_translatedToProcedures, "
        "sectionb_policymatrix_p5_hasPolicy, sectionb_policymatrix_p5_approvedByBoard, sectionb_policymatrix_p5_webLink, sectionb_policymatrix_p5_translatedToProcedures, "
        "sectionb_policymatrix_p6_hasPolicy, sectionb_policymatrix_p6_approvedByBoard, sectionb_policymatrix_p6_webLink, sectionb_policymatrix_p6_translatedToProcedures, "
        "sectionb_policymatrix_p7_hasPolicy, sectionb_policymatrix_p7_approvedByBoard, sectionb_policymatrix_p7_webLink, sectionb_policymatrix_p7_translatedToProcedures, "
        "sectionb_policymatrix_p8_hasPolicy, sectionb_policymatrix_p8_approvedByBoard, sectionb_policymatrix_p8_webLink, sectionb_policymatrix_p8_translatedToProcedures, "
        "sectionb_policymatrix_p9_hasPolicy, sectionb_policymatrix_p9_approvedByBoard, sectionb_policymatrix_p9_webLink, sectionb_policymatrix_p9_translatedToProcedures\n\n"
        "Q1c. Web Link of Policies:\n"
        "sectionb_policyWebLink (general policy web link text/URL)\n\n"
        "Q3. Value Chain Extension:\n"
        "sectionb_valueChainExtension (text describing if policies extend to value chain)\n\n"
        "Q4. Certifications:\n"
        "sectionb_certifications (comma-separated list of standards/certifications like ISO, GOTS, etc.)\n\n"
        "Q5. Commitments:\n"
        "sectionb_commitments (specific commitments, goals and targets with timelines)\n\n"
        "Q6. Performance:\n"
        "sectionb_performance (performance against commitments)\n\n"
        "Q7. Director Statement:\n"
        "sectionb_directorStatement (statement by director on ESG challenges/targets)\n\n"
        "Q8. Highest Authority:\n"
        "sectionb_highestAuthority_name, sectionb_highestAuthority_designation, sectionb_highestAuthority_din, "
        "sectionb_highestAuthority_email, sectionb_highestAuthority_phone\n\n"
        "Q9. Sustainability Committee:\n"
        "sectionb_sustainabilityCommittee (details of committee responsible for sustainability)\n\n"
        "Q10. Review of NGRBCs:\n"
        "sectionb_review_performance_p1, sectionb_review_performance_p2, sectionb_review_performance_p3, "
        "sectionb_review_performance_p4, sectionb_review_performance_p5, sectionb_review_performance_p6, "
        "sectionb_review_performance_p7, sectionb_review_performance_p8, sectionb_review_performance_p9, "
        "sectionb_review_performanceFrequency (frequency of review - Annually/Quarterly/etc.), "
        "sectionb_review_compliance (compliance review details)\n\n"
        "Q11. Independent Assessment (P1-P9):\n"
        "sectionb_independentAssessment_p1, sectionb_independentAssessment_p2, sectionb_independentAssessment_p3, "
        "sectionb_independentAssessment_p4, sectionb_independentAssessment_p5, sectionb_independentAssessment_p6, "
        "sectionb_independentAssessment_p7, sectionb_independentAssessment_p8, sectionb_independentAssessment_p9\n\n"
        "Q12. No Policy Reasons (if answer to Q1 is No):\n"
        "For each principle, extract reason why policy is not covered:\n"
        "sectionb_noPolicyReasons_notMaterial_p1 through p9 (not material to business - Y/N),\n"
        "sectionb_noPolicyReasons_notReady_p1 through p9 (not ready to formulate - Y/N),\n"
        "sectionb_noPolicyReasons_noResources_p1 through p9 (no resources - Y/N),\n"
        "sectionb_noPolicyReasons_plannedNextYear_p1 through p9 (planned next year - Y/N),\n"
        "sectionb_noPolicyReasons_otherReason_p1 through p9 (other reason text)\n\n"
        "Example output format:\n"
        '[\n'
        '  {"key": "sectionb_policymatrix_p1_hasPolicy", "value": "Y"},\n'
        '  {"key": "sectionb_policymatrix_p1_approvedByBoard", "value": "Y"},\n'
        '  {"key": "sectionb_policymatrix_p1_webLink", "value": "https://example.com/policy"},\n'
        '  {"key": "sectionb_policyWebLink", "value": "Various policies available at https://example.com"},\n'
        '  {"key": "sectionb_valueChainExtension", "value": "Yes, policies extend to suppliers"},\n'
        '  {"key": "sectionb_directorStatement", "value": "Full statement text..."}\n'
        ']\n'
    )
    return {"role": role, "goal": goal, "prompt": prompt}


def create_principles_1_2_agent() -> Dict[str, str]:
    """Return prompt payload covering Principle 1 and Principle 2 using simple key-value array format."""
    role = "BRSR Principles 1&2 Extraction Specialist"
    goal = "Extract Principle 1 and Principle 2 fields and return a JSON array of key-value pairs"
    prompt = (
        "You are an assistant that MUST output only valid JSON.\n\n"
        "Extract the following fields from the company data and output a JSON array of objects:\n"
        '[{"key": "<field_key>", "value": "<extracted_value>"}]\n\n'
        "RULES:\n"
        "- Only include fields you can extract exactly from the text\n"
        "- If a value is absent, use null or empty string\n"
        "- Do NOT add commentary or explanations\n"
        "- Output MUST be valid JSON array\n"
        "- For numbers/counts, return as strings\n"
        "- For arrays, return as JSON string array\n"
        "- Do NOT wrap output in markdown code blocks (no ``` or ```json)\n\n"
        "Fields to extract:\n\n"
        "═══════════════════════════════════════════════════════════════\n"
        "PRINCIPLE 1: BUSINESSES SHOULD CONDUCT AND GOVERN THEMSELVES WITH INTEGRITY, AND IN A MANNER THAT IS ETHICAL, TRANSPARENT AND ACCOUNTABLE\n"
        "═══════════════════════════════════════════════════════════════\n\n"
        "ESSENTIAL INDICATORS:\n\n"
        "Q1. Percentage coverage by training and awareness programmes on any of the principles during the financial year:\n"
        "TABLE STRUCTURE: Rows: Board of Directors | Key Managerial Personnel | Employees other than BoD and KMPs | Workers\n"
        "COLUMNS: Total number of training programmes | Topics/principles covered | % of persons covered\n"
        "Extract these fields:\n"
        "sectionc_principle1_essential_q1_percentagecoveredbytraining_boardofdirectors_totalprogrammes (integer count), "
        "sectionc_principle1_essential_q1_percentagecoveredbytraining_boardofdirectors_topicscovered (comma-separated topics), "
        "sectionc_principle1_essential_q1_percentagecoveredbytraining_boardofdirectors_percentagecovered (number with %), "
        "sectionc_principle1_essential_q1_percentagecoveredbytraining_kmp_totalprogrammes (integer), "
        "sectionc_principle1_essential_q1_percentagecoveredbytraining_kmp_topicscovered (comma-separated), "
        "sectionc_principle1_essential_q1_percentagecoveredbytraining_kmp_percentagecovered (% value), "
        "sectionc_principle1_essential_q1_percentagecoveredbytraining_employees_totalprogrammes (integer), "
        "sectionc_principle1_essential_q1_percentagecoveredbytraining_employees_topicscovered (comma-separated), "
        "sectionc_principle1_essential_q1_percentagecoveredbytraining_employees_percentagecovered (% value), "
        "sectionc_principle1_essential_q1_percentagecoveredbytraining_workers_totalprogrammes (integer), "
        "sectionc_principle1_essential_q1_percentagecoveredbytraining_workers_topicscovered (comma-separated), "
        "sectionc_principle1_essential_q1_percentagecoveredbytraining_workers_percentagecovered (% value)\n\n"
        "Q2. Details of fines / penalties / punishment / award / compounding fees / settlement amount paid in proceedings:\n"
        "TABLE A - MONETARY: COLUMNS: Monetary | NGRBC Principle | Name of regulatory/enforcement agency | Amount (In INR) | Brief of Case | Has appeal been preferred? (Yes/No)\n"
        "TABLE B - NON-MONETARY: COLUMNS: Non-Monetary | NGRBC Principle | Name of regulatory/enforcement agency | Brief of Case | Has appeal been preferred? (Yes/No)\n"
        "Extract as arrays:\n"
        "sectionc_principle1_essential_q2_finespenalties_monetary_array (JSON array: [{\"type\":\"Penalty/Fine/etc\",\"ngrbc\":\"P1/P2/etc\",\"regulatoryAgency\":\"Name\",\"amountInr\":\"Amount\",\"briefOfCase\":\"Details\",\"appealPreferred\":\"Yes/No\"}]), "
        "sectionc_principle1_essential_q2_finespenalties_nonmonetary_array (JSON array: [{\"type\":\"Imprisonment/etc\",\"ngrbc\":\"P1/P2/etc\",\"regulatoryAgency\":\"Name\",\"briefOfCase\":\"Details\",\"appealPreferred\":\"Yes/No\"}])\n\n"
        "Q3. Of the instances disclosed in Question 2 above, details of the Appeal / Revision preferred in cases where monetary or non-monetary action has been appealed:\n"
        "Extract: sectionc_principle1_essential_q3_appealsoutstanding (full text description or 'NIL' if none)\n\n"
        "Q4. Does the entity have an anti-corruption or anti-bribery policy? If yes, provide details in brief and if available, provide a web-link to the policy:\n"
        "Extract: sectionc_principle1_essential_q4_anticorruptionpolicy_exists (Yes/No), "
        "sectionc_principle1_essential_q4_anticorruptionpolicy_details (brief description), "
        "sectionc_principle1_essential_q4_anticorruptionpolicy_weblink (URL)\n\n"
        "Q5. Number of Directors/KMPs/employees/workers against whom disciplinary action was taken by any law enforcement agency:\n"
        "TABLE: ROWS: Directors | KMPs | Employees | Workers\n"
        "COLUMNS: FY ____ (current year) | FY ____ (previous year)\n"
        "Extract:\n"
        "sectionc_principle1_essential_q5_disciplinaryactions_directors_currentfy (integer), "
        "sectionc_principle1_essential_q5_disciplinaryactions_directors_previousfy (integer), "
        "sectionc_principle1_essential_q5_disciplinaryactions_kmps_currentfy (integer), "
        "sectionc_principle1_essential_q5_disciplinaryactions_kmps_previousfy (integer), "
        "sectionc_principle1_essential_q5_disciplinaryactions_employees_currentfy (integer), "
        "sectionc_principle1_essential_q5_disciplinaryactions_employees_previousfy (integer), "
        "sectionc_principle1_essential_q5_disciplinaryactions_workers_currentfy (integer), "
        "sectionc_principle1_essential_q5_disciplinaryactions_workers_previousfy (integer)\n\n"
        "Q6. Details of complaints with regard to conflict of interest:\n"
        "TABLE: ROWS: Directors | KMPs\n (integer), "
        "sectionc_principle1_essential_q6_conflictofinterestcomplaints_directors_currentfy_remarks (text), "
        "sectionc_principle1_essential_q6_conflictofinterestcomplaints_directors_previousfy_number (integer), "
        "sectionc_principle1_essential_q6_conflictofinterestcomplaints_directors_previousfy_remarks (text), "
        "sectionc_principle1_essential_q6_conflictofinterestcomplaints_kmps_currentfy_number (integer), "
        "sectionc_principle1_essential_q6_conflictofinterestcomplaints_kmps_currentfy_remarks (text), "
        "sectionc_principle1_essential_q6_conflictofinterestcomplaints_kmps_previousfy_number (integer), "
        "sectionc_principle1_essential_q6_conflictofinterestcomplaints_kmps_previousfy_remarks (text)\n\n"
        "Q7. Provide details of any corrective action taken or underway on issues related to fines / penalties / action taken by regulators / law enforcement agencies / judicial institutions, on cases of corruption and conflicts of interest:\n"
        "Extract: sectionc_principle1_essential_q7_correctiveactions (full text description)\n\n"
        "Q8. Number of days of accounts payables [(Accounts payable *365) / Cost of goods/services procured] in the following format:\n"
        "TABLE: COLUMNS: FY ____ (current year) | FY ____ (previous year)\n"
        "Extract: sectionc_principle1_essential_q8_accountspayabledays_currentfy (number of days), "
        "sectionc_principle1_essential_q8_accountspayabledays_previousfy (number of days)\n\n"
        "Q9. Open-ness of business - Provide details of concentration of purchases and sales with trading houses, dealers, and related parties:\n"
        "SECTION A - Concentration of Purchases:\n"
        "TABLE ROW 1: Purchases from trading houses as % of total purchases | FY ____ (current) | FY ____ (previous)\n"
        "TABLE ROW 2: Number of trading houses where purchases are made from\n"
        "TABLE ROW 3: Purchases from top 10 trading houses as % of total purchases from trading houses\n"
        "SECTION B - Concentration of Sales:\n"
        "TABLE ROW 1: Sales to dealers / distributors as % of total sales | FY ____ (current) | FY ____ (previous)\n"
        "TABLE ROW 2: Number of dealers / distributors to whom sales are made\n"
        "TABLE ROW 3: Sales to top 10 dealers / distributors as % of total sales to dealers / distributors\n"
        "SECTION C - Share of RPTs in:\n"
        "TABLE: ROWS: Purchases (A) | Sales (B) | Loans & advances (C) | Investments (D) | COLUMNS: FY ____ (current) | FY ____ (previous)\n"
        "Extract all fieldential_q7_correctiveactions, "
        "sectionc_principle1_essential_q8_accountspayabledays_currentfy, "
        "sectionc_principle1_essential_q8_accountspayabledays_previousfy\n\n"
        "Q9. Openness of business:\n"
        "sectionc_principle1_essential_q9_opennessbusiness_concentrationpurchases_tradinghousespercent_currentfy, "
        "sectionc_principle1_essential_q9_opennessbusiness_concentrationpurchases_tradinghousespercent_previousfy, "
        "sectionc_principle1_essential_q9_opennessbusiness_concentrationpurchases_dealerscount_currentfy, "
        "sectionc_principle1_essential_q9_opennessbusiness_concentrationpurchases_dealerscount_previousfy, "
        "═══════════════════════════════════════════════════════════════\n"
        "PRINCIPLE 1 - LEADERSHIP INDICATORS:\n"
        "═══════════════════════════════════════════════════════════════\n\n"
        "Q1. Awareness programmes conducted for value chain partners on any of the principles:\n"
        "TABLE: COLUMNS: Total number of awareness programmes held | Topics / principles covered | %age of value chain partners covered (by value of business done with such partners)\n"
        "Extract as array: sectionc_principle1_leadership_q1_valuechainawareness_array (JSON array: [{\"totalProgramsHeld\":\"integer\",\"topicsCovered\":\"text\",\"percentageValueChainCovered\":\"percentage\"}])\n\n"
        "Q2. Does the entity have processes in place to avoid / manage co (amount in crores), "
        "sectionc_principle2_essential_q1_rdcapexinvestments_rd_previousfy (amount in crores), "
        "sectionc_principle2_essential_q1_rdcapexinvestments_rd_improvementdetails (text description), "
        "sectionc_principle2_essential_q1_rdcapexinvestments_capex_currentfy (amount in crores), "
        "sectionc_principle2_essential_q1_rdcapexinvestments_capex_previousfy (amount in crores), "
        "sectionc_principle2_essential_q1_rdcapexinvestments_capex_improvementdetails (text description)\n\n"
        "Q2. a. Does the entity have procedures in place for sustainable sourcing? (Yes/No)\n"
        "    b. If yes, what percentage of inputs were sourced sustainably?\n"
        "Extract: sectionc_principle2_essential_q2_sustainablesourcing_proceduresinplace (Yes/No), "
        "sectionc_principle2_essential_q2_sustainablesourcing_percentagesustainablysourced (percentage value)\n\n"
        "Q3. Describe the processes in place to safely reclaim your products f (Yes/No/NA), "
        "sectionc_principle2_essential_q3_reclaimprocesses_plastics_process (description of process), "
        "sectionc_principle2_essential_q3_reclaimprocesses_ewaste_applicable (Yes/No/NA), "
        "sectionc_principle2_essential_q3_reclaimprocesses_ewaste_process (description), "
        "sectionc_principle2_essential_q3_reclaimprocesses_hazardouswaste_applicable (Yes/No/NA), "
        "sectionc_principle2_essential_q3_reclaimprocesses_hazardouswaste_process (description), "
        "sectionc_principle2_essential_q3_reclaimprocesses_otherwaste_applicable (Yes/No/NA), "
        "sectionc_principle2_essential_q3_reclaimprocesses_otherwaste_process (description)\n\n"
        "Q4. Whether Extended Producer Responsibility (EPR) is applicable to the entity's activities (Yes / No). If yes, whether the waste collection plan is in line with the Extended Producer Responsibility (EPR) plan submitted to Pollution Control Boards? If not, provide steps taken to address the same:\n"
        "Extract: sectionc_principle2_essential_q4_epr_applicable (Yes/No), "
        "sectionc_principle2_essential_q4_epr_wastecollectionplaninline (Yes/No/NA and explanation)\n\n"
        "═══════════════════════════════════════════════════════════════\n"
        "PRINCIPLE 2 - LEADERSHIP INDICATORS:\n"
        "═══════════════════════════════════════════════════════════════\n\n"
        "Q1. Has the entity conducted Life Cycle Perspective / Assessments (LCA) for any of its products? If yes, provide details:\n"
        "Extract: sectionc_principle2_leadership_q1_lcadetails (description of LCA con (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_plastics_currentfy_recycled (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_plastics_currentfy_safelydisposed (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_plastics_previousfy_reused (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_plastics_previousfy_recycled (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_plastics_previousfy_safelydisposed (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_ewaste_currentfy_reused (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_ewaste_currentfy_recycled (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_ewaste_currentfy_safelydisposed (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_ewaste_previousfy_reused (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_ewaste_previousfy_recycled (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_ewaste_previousfy_safelydisposed (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_hazardouswaste_currentfy_reused (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_hazardouswaste_currentfy_recycled (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_hazardouswaste_currentfy_safelydisposed (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_hazardouswaste_previousfy_reused (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_hazardouswaste_previousfy_recycled (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_hazardouswaste_previousfy_safelydisposed (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_otherwaste_currentfy_reused (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_otherwaste_currentfy_recycled (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_otherwaste_currentfy_safelydisposed (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_otherwaste_previousfy_reused (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_otherwaste_previousfy_recycled (metric tonnes), "
        "sectionc_principle2_leadership_q4_productsreclaimed_otherwaste_previousfy_safelydisposed (metric tonnes)\n\n"
        "Q5. Reclaimed products and their packaging materials (as percentage of products sold) for each product category:\n"
        "Extract: sectionc_principle2_leadership_q5_reclaimedpercentage (percentage or description)percentagesustainablysourced\n\n"
        "Q3. Reclaim processes:\n"
        "sectionc_principle2_essential_q3_reclaimprocesses_plastics_applicable, "
        "sectionc_principle2_essential_q3_reclaimprocesses_plastics_process, "
        "sectionc_principle2_essential_q3_reclaimprocesses_ewaste_applicable, "
        "sectionc_principle2_essential_q3_reclaimprocesses_ewaste_process, "
        "sectionc_principle2_essential_q3_reclaimprocesses_hazardouswaste_applicable, "
        "sectionc_principle2_essential_q3_reclaimprocesses_hazardouswaste_process, "
        "sectionc_principle2_essential_q3_reclaimprocesses_otherwaste_applicable, "
        "sectionc_principle2_essential_q3_reclaimprocesses_otherwaste_process\n\n"
        "Q4. EPR:\n"
        "sectionc_principle2_essential_q4_epr_applicable, "
        "sectionc_principle2_essential_q4_epr_wastecollectionplaninline\n\n"
        "PRINCIPLE 2 - Leadership Indicators:\n"
        "sectionc_principle2_leadership_q1_lcadetails, "
        "sectionc_principle2_leadership_q2_significantconcerns, "
        "sectionc_principle2_leadership_q3_recycledinputmaterial_array (JSON array: [{\"inputMaterial\":\"...\",\"currentFY\":\"...\",\"previousFY\":\"...\"}]), "
        "sectionc_principle2_leadership_q4_productsreclaimed_plastics_currentfy_reused, "
        "sectionc_principle2_leadership_q4_productsreclaimed_plastics_currentfy_recycled, "
        "sectionc_principle2_leadership_q4_productsreclaimed_plastics_currentfy_safelydisposed, "
        "sectionc_principle2_leadership_q4_productsreclaimed_plastics_previousfy_reused, "
        "sectionc_principle2_leadership_q4_productsreclaimed_plastics_previousfy_recycled, "
        "sectionc_principle2_leadership_q4_productsreclaimed_plastics_previousfy_safelydisposed, "
        "sectionc_principle2_leadership_q4_productsreclaimed_ewaste_currentfy_reused, "
        "sectionc_principle2_leadership_q4_productsreclaimed_ewaste_currentfy_recycled, "
        "sectionc_principle2_leadership_q4_productsreclaimed_ewaste_currentfy_safelydisposed, "
        "sectionc_principle2_leadership_q4_productsreclaimed_ewaste_previousfy_reused, "
        "sectionc_principle2_leadership_q4_productsreclaimed_ewaste_previousfy_recycled, "
        "sectionc_principle2_leadership_q4_productsreclaimed_ewaste_previousfy_safelydisposed, "
        "sectionc_principle2_leadership_q4_productsreclaimed_hazardouswaste_currentfy_reused, "
        "sectionc_principle2_leadership_q4_productsreclaimed_hazardouswaste_currentfy_recycled, "
        "sectionc_principle2_leadership_q4_productsreclaimed_hazardouswaste_currentfy_safelydisposed, "
        "sectionc_principle2_leadership_q4_productsreclaimed_hazardouswaste_previousfy_reused, "
        "sectionc_principle2_leadership_q4_productsreclaimed_hazardouswaste_previousfy_recycled, "
        "sectionc_principle2_leadership_q4_productsreclaimed_hazardouswaste_previousfy_safelydisposed, "
        "sectionc_principle2_leadership_q4_productsreclaimed_otherwaste_currentfy_reused, "
        "sectionc_principle2_leadership_q4_productsreclaimed_otherwaste_currentfy_recycled, "
        "sectionc_principle2_leadership_q4_productsreclaimed_otherwaste_currentfy_safelydisposed, "
        "sectionc_principle2_leadership_q4_productsreclaimed_otherwaste_previousfy_reused, "
        "sectionc_principle2_leadership_q4_productsreclaimed_otherwaste_previousfy_recycled, "
        "sectionc_principle2_leadership_q4_productsreclaimed_otherwaste_previousfy_safelydisposed, "
        "sectionc_principle2_leadership_q5_reclaimedpercentage\n\n"
        "Example output format:\n"
        '[\n'
        '  {"key": "sectionc_principle1_essential_q1_percentagecoveredbytraining_boardofdirectors_totalprogrammes", "value": "5"},\n'
        '  {"key": "sectionc_principle1_essential_q4_anticorruptionpolicy_exists", "value": "Yes"},\n'
        '  {"key": "sectionc_principle2_essential_q1_rdcapexinvestments_rd_currentfy", "value": "150.5"}\n'
        ']\n'
    )
    return {"role": role, "goal": goal, "prompt": prompt}


def create_principles_3_4_agent() -> Dict[str, str]:
    """Return prompt payload covering Principle 3 and Principle 4 using simple key-value array format."""
    role = "BRSR Principles 3&4 Extraction Specialist"
    goal = "Extract Principle 3 and 4 fields and return a JSON array of key-value pairs"
    prompt = (
        "You are an assistant that MUST output only valid JSON.\n\n"
        "Extract the following fields from the company data and output a JSON array of objects:\n"
        '[{"key": "<field_key>", "value": "<extracted_value>"}]\n\n'
        "RULES:\n"
        "- Only include fields you can extract exactly from the text\n"
        "- If a value is absent, use null or empty string\n"
        "- Do NOT add commentary or explanations\n"
        "- Output MUST be valid JSON array\n"
        "- Do NOT wrap output in markdown code blocks (no ``` or ```json)\n\n"
        "═══════════════════════════════════════════════════════════════════════════\n"
        "PRINCIPLE 3: Businesses should respect and promote the well-being of all employees, including those in their value chains\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "━━━ ESSENTIAL INDICATORS ━━━\n\n"
        "Q1a. Details of measures for the well-being of EMPLOYEES:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Permanent employees (Male | Female | Total) | Other than Permanent employees (Male | Female | Total)\n"
        "  COLUMNS: Category | Total (A) | Health insurance | Accident insurance | Maternity benefits | Paternity Benefits | Day Care facilities (Number of employees & % B/A)\n"
        "Extract: sectionc_principle3_essential_q1a_employeewellbeing_permanentmale_total (integer), "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentmale_healthinsurance_no (integer), "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentmale_healthinsurance_percent (number), "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentmale_accidentinsurance_no (integer), "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentmale_accidentinsurance_percent (number), "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentmale_maternitybenefits_no (integer), "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentmale_maternitybenefits_percent (number), "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentmale_paternitybenefits_no (integer), "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentmale_paternitybenefits_percent (number), "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentmale_daycare_no (integer), "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentmale_daycare_percent (number), "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentfemale_total (integer), "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentfemale_healthinsurance_no, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentfemale_healthinsurance_percent, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentfemale_accidentinsurance_no, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentfemale_accidentinsurance_percent, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentfemale_maternitybenefits_no, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentfemale_maternitybenefits_percent, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentfemale_paternitybenefits_no, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentfemale_paternitybenefits_percent, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentfemale_daycare_no, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanentfemale_daycare_percent, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanenttotal_total, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanenttotal_healthinsurance_no, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanenttotal_healthinsurance_percent, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanenttotal_accidentinsurance_no, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanenttotal_accidentinsurance_percent, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanenttotal_maternitybenefits_no, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanenttotal_maternitybenefits_percent, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanenttotal_paternitybenefits_no, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanenttotal_paternitybenefits_percent, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanenttotal_daycare_no, "
        "sectionc_principle3_essential_q1a_employeewellbeing_permanenttotal_daycare_percent, "
        "sectionc_principle3_essential_q1a_employeewellbeing_othermale (text), "
        "sectionc_principle3_essential_q1a_employeewellbeing_otherfemale (text), "
        "sectionc_principle3_essential_q1a_employeewellbeing_othertotal (text)\n\n"
        "Q1b. Details of measures for the well-being of WORKERS:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Permanent workers (Male | Female | Total) | Other than Permanent workers (Male | Female | Total)\n"
        "  COLUMNS: Category | Total (A) | Health insurance | Accident insurance | Maternity benefits | Paternity Benefits | Day Care facilities (Number of workers & % B/A)\n"
        "Extract: All fields similar to Q1a but with _workerwellbeing_ prefix instead of _employeewellbeing_\n"
        "sectionc_principle3_essential_q1b_workerwellbeing_permanentmale_total, "
        "sectionc_principle3_essential_q1b_workerwellbeing_permanentmale_healthinsurance_no, "
        "sectionc_principle3_essential_q1b_workerwellbeing_permanentmale_healthinsurance_percent... (and similar for female, total, other categories)\n\n"
        "Q1c. Spending on measures towards well-being of employees and workers:\n"
        "Extract: sectionc_principle3_essential_q1c_spendingonwellbeing_currentfy (number), "
        "sectionc_principle3_essential_q1c_spendingonwellbeing_previousfy (number)\n\n"
        "Q2. Details of retirement benefits (PF, Gratuity, ESI, NPS):\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: PF | Gratuity | ESI | Others (NPS)\n"
        "  COLUMNS: Current FY (Employees %, Workers %, Deducted/Deposited Y/N) | Previous FY (same)\n"
        "Extract: sectionc_principle3_essential_q2_retirementbenefits_pf_currentfy_employeespercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_pf_currentfy_workerspercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_pf_currentfy_deducteddeposited (Y/N), "
        "sectionc_principle3_essential_q2_retirementbenefits_pf_previousfy_employeespercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_pf_previousfy_workerspercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_pf_previousfy_deducteddeposited, "
        "sectionc_principle3_essential_q2_retirementbenefits_gratuity_currentfy_employeespercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_gratuity_currentfy_workerspercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_gratuity_currentfy_deducteddeposited, "
        "sectionc_principle3_essential_q2_retirementbenefits_gratuity_previousfy_employeespercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_gratuity_previousfy_workerspercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_gratuity_previousfy_deducteddeposited, "
        "sectionc_principle3_essential_q2_retirementbenefits_esi_currentfy_employeespercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_esi_currentfy_workerspercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_esi_currentfy_deducteddeposited, "
        "sectionc_principle3_essential_q2_retirementbenefits_esi_previousfy_employeespercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_esi_previousfy_workerspercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_esi_previousfy_deducteddeposited, "
        "sectionc_principle3_essential_q2_retirementbenefits_nps_currentfy_employeespercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_nps_currentfy_workerspercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_nps_currentfy_deducteddeposited, "
        "sectionc_principle3_essential_q2_retirementbenefits_nps_previousfy_employeespercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_nps_previousfy_workerspercent, "
        "sectionc_principle3_essential_q2_retirementbenefits_nps_previousfy_deducteddeposited\n\n"
        "Q3. Accessibility of workplaces - Are the premises/offices accessible to differently abled employees and workers, as per Rights of Persons with Disabilities Act, 2016?\n"
        "Extract: sectionc_principle3_essential_q3_accessibilityofworkplaces (text)\n\n"
        "Q4. Does the entity have an equal opportunity policy as per Rights of Persons with Disabilities Act, 2016? If so, provide web-link:\n"
        "Extract: sectionc_principle3_essential_q4_equalopportunitypolicy_exists (Yes/No), "
        "sectionc_principle3_essential_q4_equalopportunitypolicy_details (text/URL)\n\n"
        "Q5. Return to work and Retention rates of permanent employees and workers that took parental leave:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Male | Female | Total\n"
        "  COLUMNS: Permanent employees (Return to work rate | Retention rate) | Permanent workers (Return to work rate | Retention rate)\n"
        "Extract: sectionc_principle3_essential_q5_parentalleaverates_permanentemployees_male_returntoworkrate, "
        "sectionc_principle3_essential_q5_parentalleaverates_permanentemployees_male_retentionrate, "
        "sectionc_principle3_essential_q5_parentalleaverates_permanentemployees_female_returntoworkrate, "
        "sectionc_principle3_essential_q5_parentalleaverates_permanentemployees_female_retentionrate, "
        "sectionc_principle3_essential_q5_parentalleaverates_permanentemployees_total_returntoworkrate, "
        "sectionc_principle3_essential_q5_parentalleaverates_permanentemployees_total_retentionrate, "
        "sectionc_principle3_essential_q5_parentalleaverates_permanentworkers_male_returntoworkrate, "
        "sectionc_principle3_essential_q5_parentalleaverates_permanentworkers_male_retentionrate, "
        "sectionc_principle3_essential_q5_parentalleaverates_permanentworkers_female_returntoworkrate, "
        "sectionc_principle3_essential_q5_parentalleaverates_permanentworkers_female_retentionrate, "
        "sectionc_principle3_essential_q5_parentalleaverates_permanentworkers_total_returntoworkrate, "
        "sectionc_principle3_essential_q5_parentalleaverates_permanentworkers_total_retentionrate\n\n"
        "Q6. Mechanism to receive and redress grievances for employees and workers:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Permanent Workers | Other than Permanent Workers | Permanent Employees | Other than Permanent Employees\n"
        "  COLUMNS: Yes/No | Details of mechanism\n"
        "Extract: sectionc_principle3_essential_q6_grievancemechanism_permanentworkers, "
        "sectionc_principle3_essential_q6_grievancemechanism_otherthanpermanentworkers, "
        "sectionc_principle3_essential_q6_grievancemechanism_permanentemployees, "
        "sectionc_principle3_essential_q6_grievancemechanism_otherthanpermanentemployees, "
        "sectionc_principle3_essential_q6_grievancemechanism_details\n\n"
        "Q7. Membership of employees and workers in associations/Unions:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Total Permanent Employees | Male | Female | Total Permanent Workers | Male | Female\n"
        "  COLUMNS: Current FY (Total A | Members in Union B | % B/A) | Previous FY (Total C | Members in Union D | % D/C)\n"
        "Extract: sectionc_principle3_essential_q7_membershipunions_permanentemployees_currentfy_totalemployees, "
        "sectionc_principle3_essential_q7_membershipunions_permanentemployees_currentfy_membersinunions, "
        "sectionc_principle3_essential_q7_membershipunions_permanentemployees_currentfy_percentage, "
        "sectionc_principle3_essential_q7_membershipunions_permanentemployees_previousfy_totalemployees, "
        "sectionc_principle3_essential_q7_membershipunions_permanentemployees_previousfy_membersinunions, "
        "sectionc_principle3_essential_q7_membershipunions_permanentemployees_previousfy_percentage, "
        "sectionc_principle3_essential_q7_membershipunions_permanentworkers_currentfy_totalworkers, "
        "sectionc_principle3_essential_q7_membershipunions_permanentworkers_currentfy_membersinunions, "
        "sectionc_principle3_essential_q7_membershipunions_permanentworkers_currentfy_percentage, "
        "sectionc_principle3_essential_q7_membershipunions_permanentworkers_previousfy_totalworkers, "
        "sectionc_principle3_essential_q7_membershipunions_permanentworkers_previousfy_membersinunions, "
        "sectionc_principle3_essential_q7_membershipunions_permanentworkers_previousfy_percentage\n\n"
        "Q8. Details of training given to employees and workers:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Employees (Male | Female | Total) | Workers (Male | Female | Total)\n"
        "  COLUMNS: Current FY (Total A | Health & safety No. | Health & safety % | Skill upgradation No. | Skill upgradation %) | Previous FY (same)\n"
        "Extract all training details for employees and workers (male, female, total) for both current and previous FY\n\n"
        "Q9. Details of performance and career development reviews:\n"
        "TABLE STRUCTURE: Same as Q8 but for performance reviews\n"
        "Extract all performance review fields\n\n"
        "Q10. Health and safety management system:\n"
        "  a. Occupational health and safety management system implemented? Coverage?\n"
        "  b. Processes to identify work-related hazards and assess risks?\n"
        "  c. Processes for workers to report hazards and remove themselves from risks? (Y/N)\n"
        "  d. Employees/workers have access to non-occupational medical and healthcare services? (Y/N)\n"
        "Extract: sectionc_principle3_essential_q10_healthsafetymanagement_a, "
        "sectionc_principle3_essential_q10_healthsafetymanagement_b, "
        "sectionc_principle3_essential_q10_healthsafetymanagement_c, "
        "sectionc_principle3_essential_q10_healthsafetymanagement_d\n\n"
        "Q11. Safety related incidents:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: LTIFR (per million person-hours) | Total recordable injuries | No. of fatalities | High consequence injuries\n"
        "  COLUMNS: Employees (Current FY | Previous FY) | Workers (Current FY | Previous FY)\n"
        "Extract: sectionc_principle3_essential_q11_safetyincidents_ltifr_employees_currentyear, "
        "sectionc_principle3_essential_q11_safetyincidents_ltifr_employees_previousyear, "
        "sectionc_principle3_essential_q11_safetyincidents_ltifr_workers_currentyear, "
        "sectionc_principle3_essential_q11_safetyincidents_ltifr_workers_previousyear, "
        "sectionc_principle3_essential_q11_safetyincidents_totalrecordableinjuries_employees_currentyear, "
        "sectionc_principle3_essential_q11_safetyincidents_totalrecordableinjuries_employees_previousyear, "
        "sectionc_principle3_essential_q11_safetyincidents_totalrecordableinjuries_workers_currentyear, "
        "sectionc_principle3_essential_q11_safetyincidents_totalrecordableinjuries_workers_previousyear, "
        "sectionc_principle3_essential_q11_safetyincidents_fatalities_employees_currentyear, "
        "sectionc_principle3_essential_q11_safetyincidents_fatalities_employees_previousyear, "
        "sectionc_principle3_essential_q11_safetyincidents_fatalities_workers_currentyear, "
        "sectionc_principle3_essential_q11_safetyincidents_fatalities_workers_previousyear, "
        "sectionc_principle3_essential_q11_safetyincidents_highconsequenceinjuries_employees_currentyear, "
        "sectionc_principle3_essential_q11_safetyincidents_highconsequenceinjuries_employees_previousyear, "
        "sectionc_principle3_essential_q11_safetyincidents_highconsequenceinjuries_workers_currentyear, "
        "sectionc_principle3_essential_q11_safetyincidents_highconsequenceinjuries_workers_previousyear\n\n"
        "Q12. Describe the measures taken by the entity to ensure a safe and healthy work place:\n"
        "Extract: sectionc_principle3_essential_q12_safetymeasures (text)\n\n"
        "Q13. Number of Complaints on working conditions and health & safety:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Working Conditions | Health & Safety\n"
        "  COLUMNS: Current FY (Filed | Pending | Remarks) | Previous FY (Filed | Pending | Remarks)\n"
        "Extract: sectionc_principle3_essential_q13_complaintsworkingconditions_workingconditions_currentfy_filed, "
        "sectionc_principle3_essential_q13_complaintsworkingconditions_workingconditions_currentfy_pendingresolution, "
        "sectionc_principle3_essential_q13_complaintsworkingconditions_workingconditions_currentfy_remarks, "
        "sectionc_principle3_essential_q13_complaintsworkingconditions_workingconditions_previousfy_filed, "
        "sectionc_principle3_essential_q13_complaintsworkingconditions_workingconditions_previousfy_pendingresolution, "
        "sectionc_principle3_essential_q13_complaintsworkingconditions_workingconditions_previousfy_remarks, "
        "sectionc_principle3_essential_q13_complaintsworkingconditions_healthsafety_currentfy_filed, "
        "sectionc_principle3_essential_q13_complaintsworkingconditions_healthsafety_currentfy_pendingresolution, "
        "sectionc_principle3_essential_q13_complaintsworkingconditions_healthsafety_currentfy_remarks, "
        "sectionc_principle3_essential_q13_complaintsworkingconditions_healthsafety_previousfy_filed, "
        "sectionc_principle3_essential_q13_complaintsworkingconditions_healthsafety_previousfy_pendingresolution, "
        "sectionc_principle3_essential_q13_complaintsworkingconditions_healthsafety_previousfy_remarks\n\n"
        "Q14. Assessments for the year - % of plants/offices assessed:\n"
        "  ROWS: Health and safety practices | Working Conditions\n"
        "Extract: sectionc_principle3_essential_q14_assessments_healthsafetypractices (percentage), "
        "sectionc_principle3_essential_q14_assessments_workingconditions (percentage)\n\n"
        "Q15. Corrective actions taken for safety-related incidents and significant risks:\n"
        "Extract: sectionc_principle3_essential_q15_correctiveactions (text)\n\n"
        "━━━ LEADERSHIP INDICATORS ━━━\n\n"
        "Q1. Does the entity extend life insurance or compensatory package in death of (A) Employees (Y/N) (B) Workers (Y/N):\n"
        "Extract: sectionc_principle3_leadership_q1_lifeinsurance (text)\n\n"
        "Q2. Measures to ensure statutory dues deducted/deposited by value chain partners:\n"
        "Extract: sectionc_principle3_leadership_q2_statutoryduesvaluechain (text)\n\n"
        "Q3. Employees/workers with high consequence injury/ill-health/fatalities who have been rehabilitated:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Employees | Workers\n"
        "  COLUMNS: Current FY (Total affected | Rehabilitated) | Previous FY (Total affected | Rehabilitated)\n"
        "Extract: sectionc_principle3_leadership_q3_rehabilitation_employees_currentfy_totalaffected, "
        "sectionc_principle3_leadership_q3_rehabilitation_employees_currentfy_rehabilitated, "
        "sectionc_principle3_leadership_q3_rehabilitation_employees_previousfy_totalaffected, "
        "sectionc_principle3_leadership_q3_rehabilitation_employees_previousfy_rehabilitated, "
        "sectionc_principle3_leadership_q3_rehabilitation_workers_currentfy_totalaffected, "
        "sectionc_principle3_leadership_q3_rehabilitation_workers_currentfy_rehabilitated, "
        "sectionc_principle3_leadership_q3_rehabilitation_workers_previousfy_totalaffected, "
        "sectionc_principle3_leadership_q3_rehabilitation_workers_previousfy_rehabilitated\n\n"
        "Q4. Does entity provide transition assistance programs for continued employability and career endings? (Yes/No):\n"
        "Extract: sectionc_principle3_leadership_q4_transitionassistance\n\n"
        "Q5. Assessment of value chain partners - % assessed:\n"
        "  ROWS: Health and safety practices | Working Conditions\n"
        "Extract: sectionc_principle3_leadership_q5_valuechainassessment_healthsafetypractices (percentage), "
        "sectionc_principle3_leadership_q5_valuechainassessment_workingconditions (percentage)\n\n"
        "Q6. Corrective actions for value chain partners' health & safety and working conditions:\n"
        "Extract: sectionc_principle3_leadership_q6_correctiveactionsvaluechain (text)\n\n"
        "═══════════════════════════════════════════════════════════════════════════\n"
        "PRINCIPLE 4: Businesses should respect the interests of and be responsive to all its stakeholders\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "━━━ ESSENTIAL INDICATORS ━━━\n\n"
        "Q1. Describe the processes for identifying key stakeholder groups:\n"
        "Extract: sectionc_principle4_essential_q1_stakeholderidentification (text)\n\n"
        "Q2. List stakeholder groups identified as key and frequency of engagement:\n"
        "TABLE STRUCTURE:\n"
        "  COLUMNS: Stakeholder Group | Vulnerable & Marginalized (Y/N) | Channels of communication | Frequency | Purpose and scope\n"
        "Extract: sectionc_principle4_essential_q2_stakeholderengagement_array (JSON array of objects with fields: stakeholderGroup, vulnerableMarginalized, channels, frequency, purpose)\n"
        "Example: [{\"stakeholderGroup\":\"Employees\",\"vulnerableMarginalized\":\"No\",\"channels\":\"Email, Meetings\",\"frequency\":\"Quarterly\",\"purpose\":\"Performance reviews\"}]\n\n"
        "━━━ LEADERSHIP INDICATORS ━━━\n\n"
        "Q1. Processes for consultation between stakeholders and Board on economic, environmental, social topics:\n"
        "Extract: sectionc_principle4_leadership_q1_boardconsultation (text)\n\n"
        "Q2. Whether stakeholder consultation used to support identification/management of environmental and social topics (Yes/No). Details:\n"
        "Extract: sectionc_principle4_leadership_q2_stakeholderconsultationused (Yes/No), "
        "sectionc_principle4_leadership_q2_details_a (text), "
        "sectionc_principle4_leadership_q2_details_b (text), "
        "sectionc_principle4_leadership_q2_details_c (text)\n\n"
        "Q3. Details of engagement with vulnerable/marginalized stakeholder groups:\n"
        "Extract: sectionc_principle4_leadership_q3_vulnerableengagement_array (JSON array of objects with fields: vulnerableGroup, concerns, actionTaken)\n"
        "Example: [{\"vulnerableGroup\":\"Disabled employees\",\"concerns\":\"Accessibility\",\"actionTaken\":\"Ramps installed\"}]\n\n"
        "Example output format:\n"
        '[\n'
        '  {"key": "sectionc_principle3_essential_q1a_employeewellbeing_permanentmale_total", "value": "1500"},\n'
        '  {"key": "sectionc_principle3_essential_q2_retirementbenefits_pf_currentfy_employeespercent", "value": "92.5"},\n'
        '  {"key": "sectionc_principle4_essential_q1_stakeholderidentification", "value": "Stakeholders identified through materiality assessment"}\n'
        ']\n'
    )
    return {"role": role, "goal": goal, "prompt": prompt}


def create_principles_5_6_agent() -> Dict[str, str]:
    """Return prompt payload covering Principle 5 and Principle 6 with comprehensive BRSR format."""
    role = "BRSR Principles 5&6 Extraction Specialist"
    goal = "Extract Principle 5 and 6 fields and return a JSON array of key-value pairs"
    prompt = (
        "You are a BRSR (Business Responsibility and Sustainability Report) extraction specialist.\n"
        "Extract data for Section C: PRINCIPLE-WISE PERFORMANCE DISCLOSURE - PRINCIPLES 5 & 6.\n\n"
        
        "═══════════════════════════════════════════════════════════════════════════\n"
        "PRINCIPLE 5: Businesses should respect and promote human rights\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "━━━ ESSENTIAL INDICATORS ━━━\n\n"
        "Q1. Employees/workers whose remuneration is determined by collective agreements:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Employees (Permanent | Other than permanent | Total) | Workers (Permanent | Other than permanent | Total)\n"
        "  COLUMNS: Total (A) | Number covered by collective agreement (B) | % (B/A)\n"
        "Extract: sectionc_principle5_essential_q1_remuneration_employees_permanent_total, "
        "sectionc_principle5_essential_q1_remuneration_employees_permanent_covered, "
        "sectionc_principle5_essential_q1_remuneration_employees_permanent_percentage, "
        "sectionc_principle5_essential_q1_remuneration_employees_otherthanpermanent_total, "
        "sectionc_principle5_essential_q1_remuneration_employees_otherthanpermanent_covered, "
        "sectionc_principle5_essential_q1_remuneration_employees_otherthanpermanent_percentage, "
        "sectionc_principle5_essential_q1_remuneration_employees_totalemployees_total, "
        "sectionc_principle5_essential_q1_remuneration_employees_totalemployees_covered, "
        "sectionc_principle5_essential_q1_remuneration_employees_totalemployees_percentage, "
        "sectionc_principle5_essential_q1_remuneration_workers_permanent_total, "
        "sectionc_principle5_essential_q1_remuneration_workers_permanent_covered, "
        "sectionc_principle5_essential_q1_remuneration_workers_permanent_percentage, "
        "sectionc_principle5_essential_q1_remuneration_workers_otherthanpermanent_total, "
        "sectionc_principle5_essential_q1_remuneration_workers_otherthanpermanent_covered, "
        "sectionc_principle5_essential_q1_remuneration_workers_otherthanpermanent_percentage, "
        "sectionc_principle5_essential_q1_remuneration_workers_totalworkers_total, "
        "sectionc_principle5_essential_q1_remuneration_workers_totalworkers_covered, "
        "sectionc_principle5_essential_q1_remuneration_workers_totalworkers_percentage\n\n"
        "Q2. Details of remuneration/salary/wages >= minimum wages:\n"
        "LARGE TABLE: 2 Financial Years × (Employees: Permanent/Other × Male/Female) + (Workers: Permanent/Other × Male/Female)\n"
        "For EACH: Total (A) | Equal to Minimum Wage (Number & %) | More than Minimum Wage (Number & %)\n"
        "Extract ALL 96 fields (employees_permanent_male through workers_otherthanpermanent_female for currentfy/previousfy)\n\n"
        "Q3. Gross wages paid to males and females:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Board of Directors | Key Managerial Personnel | Employees other than BoD and KMP | Workers\n"
        "  COLUMNS: Male (Number | Median gross wages) | Female (Number | Median gross wages)\n"
        "Extract: sectionc_principle5_essential_q3_medianremuneration_boardofdirectors_male_number, "
        "sectionc_principle5_essential_q3_medianremuneration_boardofdirectors_male_median, "
        "sectionc_principle5_essential_q3_medianremuneration_boardofdirectors_female_number, "
        "sectionc_principle5_essential_q3_medianremuneration_boardofdirectors_female_median, "
        "sectionc_principle5_essential_q3_medianremuneration_keymanagerialpersonnel_male_number, "
        "sectionc_principle5_essential_q3_medianremuneration_keymanagerialpersonnel_male_median, "
        "sectionc_principle5_essential_q3_medianremuneration_keymanagerialpersonnel_female_number, "
        "sectionc_principle5_essential_q3_medianremuneration_keymanagerialpersonnel_female_median, "
        "sectionc_principle5_essential_q3_medianremuneration_employeesotherthanbodandkmp_male_number, "
        "sectionc_principle5_essential_q3_medianremuneration_employeesotherthanbodandkmp_male_median, "
        "sectionc_principle5_essential_q3_medianremuneration_employeesotherthanbodandkmp_female_number, "
        "sectionc_principle5_essential_q3_medianremuneration_employeesotherthanbodandkmp_female_median, "
        "sectionc_principle5_essential_q3_medianremuneration_workers_male_number, "
        "sectionc_principle5_essential_q3_medianremuneration_workers_male_median, "
        "sectionc_principle5_essential_q3_medianremuneration_workers_female_number, "
        "sectionc_principle5_essential_q3_medianremuneration_workers_female_median\n\n"
        "Q3a. Gross wages paid to females as % of total wages (Current FY & Previous FY):\n"
        "Extract: sectionc_principle5_essential_q3a_grosswagesfemales_currentfy, "
        "sectionc_principle5_essential_q3a_grosswagesfemales_previousfy\n\n"
        "Q4. Focal point/individual or committee for human rights issues:\n"
        "Extract: sectionc_principle5_essential_q4_focalpointhumanrights (text)\n\n"
        "Q5. Internal mechanisms to redress grievances related to human rights:\n"
        "Extract: sectionc_principle5_essential_q5_grievancemechanisms (text)\n\n"
        "Q6. Number of complaints filed during the year:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Sexual Harassment | Discrimination at workplace | Child Labour | Forced/Involuntary Labour | Wages | Other human rights\n"
        "  COLUMNS: Current FY (Filed | Pending | Remarks) | Previous FY (Filed | Pending | Remarks)\n"
        "Extract: sectionc_principle5_essential_q6_complaints_sexualharassment_currentfy_filed, "
        "sectionc_principle5_essential_q6_complaints_sexualharassment_currentfy_pending, "
        "sectionc_principle5_essential_q6_complaints_sexualharassment_currentfy_remarks, "
        "sectionc_principle5_essential_q6_complaints_sexualharassment_previousfy_filed, "
        "sectionc_principle5_essential_q6_complaints_sexualharassment_previousfy_pending, "
        "sectionc_principle5_essential_q6_complaints_sexualharassment_previousfy_remarks, "
        "(continue for discriminationatworkplace, childlabour, forcedlabour, wages, otherhumanrights)\n\n"
        "Q7. Complaints on POSH:\n"
        "Extract: sectionc_principle5_essential_q7_poshcomplaints_totalcomplaints_currentfy, "
        "sectionc_principle5_essential_q7_poshcomplaints_totalcomplaints_previousfy, "
        "sectionc_principle5_essential_q7_poshcomplaints_complaintsaspercentfemale_currentfy, "
        "sectionc_principle5_essential_q7_poshcomplaints_complaintsaspercentfemale_previousfy, "
        "sectionc_principle5_essential_q7_poshcomplaints_complaintsupheld_currentfy, "
        "sectionc_principle5_essential_q7_poshcomplaints_complaintsupheld_previousfy\n\n"
        "Q8. Mechanisms to prevent adverse consequences to complainant:\n"
        "Extract: sectionc_principle5_essential_q8_mechanismspreventadverseconsequences (text)\n\n"
        "Q9. Do human rights requirements form part of business agreements:\n"
        "Extract: sectionc_principle5_essential_q9_humanrightsincontracts (text)\n\n"
        "Q10. Assessments for the year (% of value chain partners assessed):\n"
        "Extract: sectionc_principle5_essential_q10_assessments_childlabour, "
        "sectionc_principle5_essential_q10_assessments_forcedinvoluntarylabour, "
        "sectionc_principle5_essential_q10_assessments_sexualharassment, "
        "sectionc_principle5_essential_q10_assessments_discriminationatworkplace, "
        "sectionc_principle5_essential_q10_assessments_wages, "
        "sectionc_principle5_essential_q10_assessments_othersspecify\n\n"
        "Q11. Corrective action taken or underway for significant risks:\n"
        "Extract: sectionc_principle5_essential_q11_correctiveactions (text)\n\n"
        "━━━ LEADERSHIP INDICATORS ━━━\n\n"
        "Q1. Details of business process modification to address human rights:\n"
        "Extract: sectionc_principle5_leadership_q1_businessprocessmodified (text)\n\n"
        "Q2. Assessment and commitments related to human rights policy:\n"
        "Extract: sectionc_principle5_leadership_q2_humanrightsduediligence (text)\n\n"
        "Q3. Consideration of accessibility for differently-abled persons:\n"
        "Extract: sectionc_principle5_leadership_q3_accessibilitydifferentlyabled (text)\n\n"
        "Q4. Assessments for value chain partners (% assessed):\n"
        "Extract: sectionc_principle5_leadership_q4_valuechainassessment_sexualharassment, "
        "sectionc_principle5_leadership_q4_valuechainassessment_discriminationatworkplace, "
        "sectionc_principle5_leadership_q4_valuechainassessment_childlabour, "
        "sectionc_principle5_leadership_q4_valuechainassessment_forcedlabourinvoluntarylabour, "
        "sectionc_principle5_leadership_q4_valuechainassessment_wages, "
        "sectionc_principle5_leadership_q4_valuechainassessment_othersspecify\n\n"
        "Q5. Corrective action for value chain partners:\n"
        "Extract: sectionc_principle5_leadership_q5_correctiveactionsvaluechain (text)\n\n"
        
        "═══════════════════════════════════════════════════════════════════════════\n"
        "PRINCIPLE 6: Businesses should respect and make efforts to protect and restore the environment\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "━━━ ESSENTIAL INDICATORS ━━━\n\n"
        "Q1. Total energy consumed (Joules or multiples) with sources:\n"
        "TABLE STRUCTURE:\n"
        "  SECTIONS: From renewable sources | From non-renewable sources\n"
        "  ROWS: Electricity | Fuel | Other sources | Total\n"
        "  Additional: Total energy consumed | Energy intensity per rupee turnover | Energy intensity (optional - per product/PPP) | External assessment\n"
        "Extract: sectionc_principle6_essential_q1_energyconsumption_renewable_electricity_currentfy, "
        "sectionc_principle6_essential_q1_energyconsumption_renewable_electricity_previousfy, "
        "sectionc_principle6_essential_q1_energyconsumption_renewable_fuel_currentfy, "
        "sectionc_principle6_essential_q1_energyconsumption_renewable_fuel_previousfy, "
        "sectionc_principle6_essential_q1_energyconsumption_renewable_othersources_currentfy, "
        "sectionc_principle6_essential_q1_energyconsumption_renewable_othersources_previousfy, "
        "sectionc_principle6_essential_q1_energyconsumption_renewable_total_currentfy, "
        "sectionc_principle6_essential_q1_energyconsumption_renewable_total_previousfy, "
        "(continue for nonrenewable sources, totalenergyconsumed, energyintensityperturnover, energyintensityppp, energyintensityphysicaloutput, externalassessment)\n\n"
        "Q2. Does entity have any sites under the PAT Scheme:\n"
        "Extract: sectionc_principle6_essential_q2_patscheme (Yes/No), "
        "sectionc_principle6_essential_q2_patfacilities_array (JSON array if applicable)\n\n"
        "Q3. Water withdrawal, consumption and discharge:\n"
        "  Withdrawal from: Surface water | Groundwater | Third party | Seawater/desalinated | Others | Total\n"
        "  Consumption: Total\n"
        "  Intensity: Per rupee turnover | (Optional) Per product/PPP\n"
        "  External assessment\n"
        "Extract all fields starting with: sectionc_principle6_essential_q3_waterdetails_withdrawal_surfacewater_currentfy...\n\n"
        "Q4. Water discharge in format of Question 3:\n"
        "  Discharge to: Surface water | Groundwater | Seawater | Third parties | Others | Total\n"
        "  For each: Into location with no treatment | Into location with treatment\n"
        "Extract: sectionc_principle6_essential_q4_waterdischarge_surfacewater_notreatment_currentfy, "
        "sectionc_principle6_essential_q4_waterdischarge_surfacewater_withtreatment_currentfy...\n\n"
        "Q5. Has the entity implemented zero liquid discharge:\n"
        "Extract: sectionc_principle6_essential_q5_zeroliquiddischarge\n\n"
        "Q6. Air emissions parameters (Current FY & Previous FY):\n"
        "  Pollutants: NOx | SOx | PM | POP | VOC | HAP | Others\n"
        "  For EACH: Unit | Current FY | Previous FY\n"
        "  External assessment\n"
        "Extract: sectionc_principle6_essential_q6_airemissions_nox_unit, "
        "sectionc_principle6_essential_q6_airemissions_nox_currentfy, "
        "sectionc_principle6_essential_q6_airemissions_nox_previousfy, "
        "(continue for sox, pm, pop, voc, hap, others, externalassessment)\n\n"
        "Q7. Greenhouse gas emissions (Scope 1 & 2):\n"
        "  Rows: Scope 1 | Scope 2 | Total Scope 1 + 2 | Total Scope 1 + 2 intensity per rupee turnover | (Optional) intensity\n"
        "  For each: Unit | Current FY | Previous FY\n"
        "Extract: sectionc_principle6_essential_q7_ghgemissions_scope1_unit, "
        "sectionc_principle6_essential_q7_ghgemissions_scope1_currentfy, "
        "sectionc_principle6_essential_q7_ghgemissions_scope1_previousfy, "
        "(continue for scope2, totalscope1and2, scope1and2intensityperturnover, scope1and2intensityphysicaloutput, externalassessment)\n\n"
        "Q8. GHG emission reduction projects:\n"
        "Extract: sectionc_principle6_essential_q8_ghgreductionprojects (text)\n\n"
        "Q9. Waste management (Current FY & Previous FY):\n"
        "  Types: Plastic | E-waste | Bio-medical | Construction/demolition | Battery | Radioactive | Other hazardous | Other non-hazardous | Total\n"
        "  Intensity: Per rupee turnover | (Optional) Per product/PPP\n"
        "  Recovery: Recycled | Re-used | Other recovery | Total\n"
        "  Disposal: Incineration | Landfilling | Other disposal | Total\n"
        "Extract all 29 fields\n\n"
        "Q10. Briefly describe waste management practices:\n"
        "Extract: sectionc_principle6_essential_q10_wastepractices\n\n"
        "Q11. Ecologically sensitive areas:\n"
        "Extract: sectionc_principle6_essential_q11_ecologicallysensitiveareas, "
        "sectionc_principle6_essential_q11_ecologicallysensitivedetails\n\n"
        "Q12. Environmental impact assessments:\n"
        "Extract: sectionc_principle6_essential_q12_environmentalimpactassessments\n\n"
        "Q13. Environmental compliance:\n"
        "Extract: sectionc_principle6_essential_q13_environmentalcompliance, "
        "sectionc_principle6_essential_q13_noncompliances\n\n"
        "━━━ LEADERSHIP INDICATORS ━━━\n\n"
        "Q1. Water withdrawal/consumption/discharge in water-stress areas:\n"
        "  Name | Nature of operations\n"
        "  Withdrawal (6 sources) | Consumption | Intensity | Discharge (5 destinations with/without treatment)\n"
        "Extract all 42 fields\n\n"
        "Q2. Scope 3 emissions:\n"
        "Extract: sectionc_principle6_leadership_q2_scope3emissions, "
        "sectionc_principle6_leadership_q2_scope3emissionsperturnover, "
        "sectionc_principle6_leadership_q2_scope3intensityphysicaloutput, "
        "sectionc_principle6_leadership_q2_externalassessment\n\n"
        "Q3. Biodiversity impact:\n"
        "Extract: sectionc_principle6_leadership_q3_biodiversityimpact\n\n"
        "Q4. Resource efficiency initiatives:\n"
        "Extract: sectionc_principle6_leadership_q4_resourceefficiencyinitiatives_array (JSON array)\n\n"
        "Q5. Business continuity plan:\n"
        "Extract: sectionc_principle6_leadership_q5_businesscontinuityplan\n\n"
        "Q6. Value chain environmental impact:\n"
        "Extract: sectionc_principle6_leadership_q6_valuechainenvironmentalimpact\n\n"
        "Q7. % of value chain partners assessed:\n"
        "Extract: sectionc_principle6_leadership_q7_valuechainpartnersassessed\n\n"
        
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "OUTPUT FORMAT:\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "Return ONLY a JSON array of objects. Each object must have exactly two properties: \"key\" and \"value\".\n"
        "For tables, extract EACH CELL as a separate object.\n"
        "For text fields, extract as \"key\":\"field_name\", \"value\":\"extracted text\".\n"
        "For numeric/percentage fields, include the unit/% symbol in the value.\n"
        "For arrays (_array suffix), extract as JSON array string in the value field.\n"
        "Always return valid JSON. Do not add explanations or comments.\n\n"
        "Example output:\n"
        "[\n"
        "  {\"key\": \"sectionc_principle5_essential_q1_remuneration_employees_permanent_total\", \"value\": \"500\"},\n"
        "  {\"key\": \"sectionc_principle6_essential_q1_energyconsumption_renewable_electricity_currentfy\", \"value\": \"1500 MWh\"},\n"
        "  {\"key\": \"sectionc_principle6_essential_q6_airemissions_nox_unit\", \"value\": \"kg\"}\n"
        "]\n"
    )
    return {"role": role, "goal": goal, "prompt": prompt}


def create_principles_7_8_9_agent() -> Dict[str, str]:
    """Return prompt payload covering Principles 7, 8 and 9 with comprehensive BRSR format."""
    role = "BRSR Principles 7,8,9 Extraction Specialist"
    goal = "Extract Principles 7, 8 and 9 fields and return a JSON array of key-value pairs"
    prompt = (
        "You are a BRSR (Business Responsibility and Sustainability Report) extraction specialist.\n"
        "Extract data for Section C: PRINCIPLE-WISE PERFORMANCE DISCLOSURE - PRINCIPLES 7, 8 & 9.\n\n"
        
        "═══════════════════════════════════════════════════════════════════════════\n"
        "PRINCIPLE 7: Businesses, when engaging in influencing public and regulatory policy, should do so in a manner that is responsible and transparent\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "━━━ ESSENTIAL INDICATORS ━━━\n\n"
        "Q1a. Number of affiliations with trade and industry chambers/associations:\n"
        "Extract: sectionc_principle7_essential_q1a_numberofaffiliations (number)\n\n"
        "Q1b. List the top 10 trade and industry chambers/associations:\n"
        "TABLE STRUCTURE:\n"
        "  COLUMNS: Name of the trade and industry chambers/associations | Reach (State/National)\n"
        "Extract: sectionc_principle7_essential_q1b_affiliationslist_array (JSON array of objects)\n"
        "Example: [{\"name\":\"CII\",\"reach\":\"National\"},{\"name\":\"FICCI\",\"reach\":\"National\"}]\n\n"
        "Q2. Details of corrective action taken or underway on anti-competitive conduct:\n"
        "Extract: sectionc_principle7_essential_q2_anticompetitiveconduct (text)\n\n"
        "━━━ LEADERSHIP INDICATORS ━━━\n\n"
        "Q1. Details of public policy positions advocated:\n"
        "TABLE STRUCTURE:\n"
        "  COLUMNS: Public policy advocated | Method resorted | Availability in public domain (Yes/No) | Frequency of review | Web Link\n"
        "Extract: sectionc_principle7_leadership_q1_publicpolicyadvocacy_array (JSON array)\n"
        "Example: [{\"policyAdvocated\":\"Tax reforms\",\"methodResorted\":\"Direct engagement\",\"publicDomain\":\"Yes\",\"frequencyOfReview\":\"Quarterly\",\"webLink\":\"https://...\"}]\n\n"
        
        "═══════════════════════════════════════════════════════════════════════════\n"
        "PRINCIPLE 8: Businesses should promote inclusive growth and equitable development\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "━━━ ESSENTIAL INDICATORS ━━━\n\n"
        "Q1. Details of Social Impact Assessments (SIA) of projects:\n"
        "Extract: sectionc_principle8_essential_q1_socialimpactassessments (text)\n\n"
        "Q2. Information on project(s) for which rehabilitation and resettlement undertaken:\n"
        "Extract: sectionc_principle8_essential_q2_rehabilitationresettlement (text)\n\n"
        "Q3. Mechanism to receive and redress grievances of the community:\n"
        "Extract: sectionc_principle8_essential_q3_communitygrievancemechanism (text)\n\n"
        "Q4. Percentage of input material sourced from suppliers:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Directly sourced from MSMEs/small producers | Sourced directly from within the district and neighbouring districts\n"
        "  COLUMNS: Current FY | Previous FY\n"
        "Extract: sectionc_principle8_essential_q4_inputmaterialsourcing_msmes_currentfy, "
        "sectionc_principle8_essential_q4_inputmaterialsourcing_msmes_previousfy, "
        "sectionc_principle8_essential_q4_inputmaterialsourcing_withindistrict_currentfy, "
        "sectionc_principle8_essential_q4_inputmaterialsourcing_withindistrict_previousfy, "
        "sectionc_principle8_essential_q4_inputmaterialsourcing_neighboringdistricts_currentfy, "
        "sectionc_principle8_essential_q4_inputmaterialsourcing_neighboringdistricts_previousfy\n\n"
        "Q5. Job creation in smaller towns (< 1 lakh in population):\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Rural | Semi-urban | Urban | Metropolitan\n"
        "  COLUMNS: Current FY | Previous FY\n"
        "Extract: sectionc_principle8_essential_q5_jobcreation_rural_currentfy, "
        "sectionc_principle8_essential_q5_jobcreation_rural_previousfy, "
        "sectionc_principle8_essential_q5_jobcreation_semiurban_currentfy, "
        "sectionc_principle8_essential_q5_jobcreation_semiurban_previousfy, "
        "sectionc_principle8_essential_q5_jobcreation_urban_currentfy, "
        "sectionc_principle8_essential_q5_jobcreation_urban_previousfy, "
        "sectionc_principle8_essential_q5_jobcreation_metropolitan_currentfy, "
        "sectionc_principle8_essential_q5_jobcreation_metropolitan_previousfy\n\n"
        "━━━ LEADERSHIP INDICATORS ━━━\n\n"
        "Q1. Actions to mitigate negative social impacts:\n"
        "Extract: sectionc_principle8_leadership_q1_negativeimpactmitigation (text)\n\n"
        "Q2. Details of CSR amount spent in aspirational districts:\n"
        "TABLE STRUCTURE:\n"
        "  COLUMNS: State | Aspirational District | Amount Spent (In INR)\n"
        "Extract: sectionc_principle8_leadership_q2_csrprojects_array (JSON array)\n"
        "Example: [{\"state\":\"Bihar\",\"aspirationalDistrict\":\"Gaya\",\"amountSpent\":\"10000000\"}]\n\n"
        "Q3a. Preferential procurement from MSMEs/small producers:\n"
        "Extract: sectionc_principle8_leadership_q3a_preferentialprocurement (text)\n\n"
        "Q3b. Details of sourcing from marginalized/vulnerable groups:\n"
        "Extract: sectionc_principle8_leadership_q3b_vulnerablegroups (text)\n\n"
        "Q3c. What percentage of total procurement spent on local and small producers:\n"
        "Extract: sectionc_principle8_leadership_q3c_procurementpercentage (text)\n\n"
        "Q4. Intellectual property rights owned/held:\n"
        "Extract: sectionc_principle8_leadership_q4_intellectualproperty (text)\n\n"
        "Q5. Corrective actions on IP infringement disputes:\n"
        "Extract: sectionc_principle8_leadership_q5_ipdisputes (text)\n\n"
        "Q6. Details of beneficiaries of CSR Projects:\n"
        "TABLE STRUCTURE:\n"
        "  COLUMNS: CSR Project | No. of persons benefited | % of beneficiaries from vulnerable and marginalized groups\n"
        "Extract: sectionc_principle8_leadership_q6_csrbeneficiaries_array (JSON array)\n"
        "Example: [{\"project\":\"Education\",\"beneficiaries\":\"5000\",\"percentVulnerable\":\"60%\"}]\n\n"
        
        "═══════════════════════════════════════════════════════════════════════════\n"
        "PRINCIPLE 9: Businesses should engage with and provide value to their consumers in a responsible manner\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "━━━ ESSENTIAL INDICATORS ━━━\n\n"
        "Q1. Mechanisms to receive and respond to consumer complaints and feedback:\n"
        "Extract: sectionc_principle9_essential_q1_consumercomplaintmechanism (text)\n\n"
        "Q2. Product information required by regulations displayed on product over and above legal requirements:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Environmental and social parameters relevant to product | Information related to safe and responsible usage | Recycling and/or safe disposal\n"
        "Extract: sectionc_principle9_essential_q2_productinformationpercentage_environmentalparameters (percentage), "
        "sectionc_principle9_essential_q2_productinformationpercentage_safeusage (percentage), "
        "sectionc_principle9_essential_q2_productinformationpercentage_recycling (percentage)\n\n"
        "Q3. Number of consumer complaints:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Data privacy | Advertising | Cyber-security | Delivery of essential services | Restrictive Trade Practices | Unfair Trade Practices | Other\n"
        "  COLUMNS: Current FY (Received | Pending | Remarks) | Previous FY (Received | Pending | Remarks)\n"
        "Extract: sectionc_principle9_essential_q3_consumercomplaints_dataprivacy_currentfy_received, "
        "sectionc_principle9_essential_q3_consumercomplaints_dataprivacy_currentfy_pending, "
        "sectionc_principle9_essential_q3_consumercomplaints_dataprivacy_currentfy_remarks, "
        "sectionc_principle9_essential_q3_consumercomplaints_dataprivacy_previousfy_received, "
        "sectionc_principle9_essential_q3_consumercomplaints_dataprivacy_previousfy_pending, "
        "sectionc_principle9_essential_q3_consumercomplaints_dataprivacy_previousfy_remarks, "
        "(continue for advertising, cybersecurity, deliveryofessentialservices, restrictivetradepractices, unfairtradepractices, other)\n\n"
        "Q4. Details of instances of product recalls:\n"
        "TABLE STRUCTURE:\n"
        "  ROWS: Voluntary recalls | Forced recalls\n"
        "  COLUMNS: Number | Reasons for recall\n"
        "Extract: sectionc_principle9_essential_q4_productrecalls_voluntary_number, "
        "sectionc_principle9_essential_q4_productrecalls_voluntary_reasons, "
        "sectionc_principle9_essential_q4_productrecalls_forced_number, "
        "sectionc_principle9_essential_q4_productrecalls_forced_reasons\n\n"
        "Q5. Framework/policy on cyber security and risks related to data privacy:\n"
        "Extract: sectionc_principle9_essential_q5_cybersecuritypolicy (text)\n\n"
        "Q6. Corrective actions on cases related to advertising/unfair trade practices:\n"
        "Extract: sectionc_principle9_essential_q6_correctiveactions (text)\n\n"
        "Q7. Instances of data breaches:\n"
        "Extract: sectionc_principle9_essential_q7_databreaches_a_numberofinstances (number), "
        "sectionc_principle9_essential_q7_databreaches_b_impactonbusiness (text)\n\n"
        "Q8. Turnover of products and services sold as percentage of overall turnover:\n"
        "Extract: sectionc_principle9_essential_q8_turnoversafety_a_environmentallysustainableproducts (percentage), "
        "sectionc_principle9_essential_q8_turnoversafety_b_saferecyclableproducts (percentage)\n\n"
        "━━━ LEADERSHIP INDICATORS ━━━\n\n"
        "Q1. Channels/platforms to receive feedback from consumers:\n"
        "Extract: sectionc_principle9_leadership_q1_informationchannels (text)\n\n"
        "Q2. Steps taken on consumer satisfaction surveys:\n"
        "Extract: sectionc_principle9_leadership_q2_consumersurveys_trendsinsatisfaction (text), "
        "sectionc_principle9_leadership_q2_consumersurveys_areasofimpact (text)\n\n"
        
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "OUTPUT FORMAT:\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "Return ONLY a JSON array of objects. Each object must have exactly two properties: \"key\" and \"value\".\n"
        "For tables, extract EACH CELL as a separate object.\n"
        "For text fields, extract as \"key\":\"field_name\", \"value\":\"extracted text\".\n"
        "For numeric/percentage fields, include the unit/% symbol in the value.\n"
        "For arrays (_array suffix), extract as JSON array string in the value field.\n"
        "Always return valid JSON. Do not add explanations or comments.\n\n"
        "Example output:\n"
        "[\n"
        "  {\"key\": \"sectionc_principle7_essential_q1a_numberofaffiliations\", \"value\": \"15\"},\n"
        "  {\"key\": \"sectionc_principle8_essential_q4_inputmaterialsourcing_msmes_currentfy\", \"value\": \"45%\"},\n"
        "  {\"key\": \"sectionc_principle9_essential_q3_consumercomplaints_dataprivacy_currentfy_received\", \"value\": \"10\"}\n"
        "]\n"
    )
    return {"role": role, "goal": goal, "prompt": prompt}


__all__ = [
    "create_sectionA_agent",
    "create_sectionB_agent",
    "create_principles_1_2_agent",
    "create_principles_3_4_agent",
    "create_principles_5_6_agent",
    "create_principles_7_8_9_agent",
]
